-   comment: ''
    creator: Bielawski Wojciech (wro03037.ClearCaseUsersWROI@wro3037c)
    datetime: '2008-08-28T10:06:23+02:00'
    elementtype: text_file
    protection:
        group:
            name: PL_WRO_CC_USR
            rights: r--
        other:
            name: ''
            rights: r--
        user:
            name: wrocc_adm
            rights: r--
    type: file
    version:
        branch: /main
        name: header_common.inc
        nr: '0'
        path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html/includes
-   comment: ''
    creator: '#Funktionskennung (ccalbd_bch.ccusers@bchk4qcc)'
    datetime: '2008-08-28T12:14:41+02:00'
    elementtype: text_file
    predecessor:
        branch: /main
        nr: '0'
    protection:
        group:
            name: PL_WRO_CC_USR
            rights: r--
        other:
            name: ''
            rights: r--
        user:
            name: wrocc_adm
            rights: r--
    type: file
    version:
        branch: /main/porta_bas_052_maint
        name: header_common.inc
        nr: '0'
        path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html/includes
-   comment: '"tcom dlv"'
    creator: Wiecek Pawel (wro02419.ClearCaseUsersWROI@wro2419c)
    datetime: '2008-09-04T14:07:42+02:00'
    elementtype: text_file
    labels:
    - PORTA_MAINT_BAS_052_011_313
    - PORTA_MAINT_BAS_052_011_312
    - PORTA_MAINT_BAS_052_011_311
    - PORTA_MAINT_BAS_052_011_310
    - PORTA_MAINT_BAS_052_011_302
    - PORTA_MAINT_BAS_052_011_301
    - PORTA_MAINT_BAS_052_011_300
    - PORTA_MAINT_BAS_052_011_300_T2
    - PORTA_MAINT_BAS_052_011_300_T1
    - PORTA_FRONTIER_BAS_000
    - PORTA_MAINT_BAS_052_011_200
    - PORTA_MAINT_BAS_052_011_100
    - PORTA_MAINT_BAS_052_011
    - PORTA_MAINT_BAS_052_011_T
    predecessor:
        branch: /main/porta_bas_052_maint
        nr: '0'
    protection:
        group:
            name: PL_WRO_CC_USR
            rights: r--
        other:
            name: ''
            rights: r--
        user:
            name: wrocc_adm
            rights: r--
    type: file
    version:
        branch: /main/porta_bas_052_maint
        name: header_common.inc
        nr: '1'
        path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html/includes
-   comment: ''
    creator: Zatorski Michal (wroshc0012.ClearCaseUsersWROI@wroe3634c)
    datetime: '2008-10-29T15:40:46+01:00'
    elementtype: text_file
    predecessor:
        branch: /main/porta_bas_052_maint
        nr: '1'
    protection:
        group:
            name: PL_WRO_CC_USR
            rights: r--
        other:
            name: ''
            rights: r--
        user:
            name: wrocc_adm
            rights: r--
    type: file
    version:
        branch: /main/porta_bas_052_maint/dev_wro_porta_bas_052_maint
        name: header_common.inc
        nr: '0'
        path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html/includes
-   comment: '"CAFT 2607 feature 9.  {{dlv /dev_wroshc0012_porta_bas_052_maint/1}}"'
    creator: Zatorski Michal (wroshc0012.ClearCaseUsersWROI@wroe3634c)
    datetime: '2008-10-29T15:54:48+01:00'
    elementtype: text_file
    predecessor:
        branch: /main/porta_bas_052_maint/dev_wro_porta_bas_052_maint
        nr: '0'
    protection:
        group:
            name: PL_WRO_CC_USR
            rights: r--
        other:
            name: ''
            rights: r--
        user:
            name: wrocc_adm
            rights: r--
    type: file
    version:
        branch: /main/porta_bas_052_maint/dev_wro_porta_bas_052_maint
        name: header_common.inc
        nr: '1'
        path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html/includes
-   comment: "\"caft 2571  {{dlv /dev_wro04012_porta_bas_052_maint/1}}\n   Rebased\
        \ to PORTA_BAS_052_MAINT_DEV_WRO_04012  {{dlv /dev_wro04012_porta_bas_052_maint/2}}\""
    creator: Borowski Przemyslaw (wro04012.ClearCaseUsersWROI@wro4012c)
    datetime: '2008-11-05T08:11:00+01:00'
    elementtype: text_file
    labels:
    - skawinsk_m_ext
    - mocek_dari
    - MOCEK_DARI_PORTA_BAS_052_MAINT_SIB
    - WIECEK_PORTA_MAINT_52_PREINT_15AX
    - wiecek_paw
    - mandziej_z_ext
    - langiewi_m
    - kalinows_b
    - bielawsk_w
    - borowski_p
    - pilka_dari
    - zlomek_kry
    - zatorski_m
    - zarczyns_a
    - PORTA_BAS_052_MAINT_DEV_WRO_000
    - PORTA_BAS_052_MAINT_DEV_WRO_shc0036
    - PORTA_BAS_052_MAINT_DEV_WRO_02419
    - PORTA_BAS_052_MAINT_DEV_WRO_e3727
    - PORTA_BAS_052_MAINT_DEV_WRO_shc0012
    - PORTA_BAS_052_MAINT_DEV_WRO_04122
    - PORTA_BAS_052_MAINT_DEV_WRO_04012
    - PORTA_BAS_052_MAINT_DEV_WRO_03037
    - PORTA_BAS_052_MAINT_DEV_WRO_04294
    - PORTA_BAS_052_MAINT_DEV_WRO_01565
    - PORTA_BAS_052_MAINT_DEV_WRO_01662
    - PORTA_BAS_052_MAINT_DEV_WRO_04030
    predecessor:
        branch: /main/porta_bas_052_maint/dev_wro_porta_bas_052_maint
        nr: '1'
    protection:
        group:
            name: PL_WRO_CC_USR
            rights: r--
        other:
            name: ''
            rights: r--
        user:
            name: wrocc_adm
            rights: r--
    type: file
    version:
        branch: /main/porta_bas_052_maint/dev_wro_porta_bas_052_maint
        name: header_common.inc
        nr: '2'
        path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html/includes
