-   comment: ''
    creator: Borowski Przemyslaw (wro04012.ClearCaseUsersWROI@wro4012c)
    datetime: '2008-07-11T15:13:29+02:00'
    elementtype: compressed_file
    protection:
        group:
            name: PL_WRO_CC_USR
            rights: r--
        other:
            name: ''
            rights: r--
        user:
            name: wrocc_adm
            rights: r--
    type: file
    version:
        branch: /main
        name: lib_isps_annex_b.inc
        nr: '0'
        path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html/includes
-   comment: ''
    creator: '#Funktionskennung (ccalbd_bch.ccusers@bchk4qcc)'
    datetime: '2008-07-11T16:27:04+02:00'
    elementtype: compressed_file
    predecessor:
        branch: /main
        nr: '0'
    protection:
        group:
            name: PL_WRO_CC_USR
            rights: r--
        other:
            name: ''
            rights: r--
        user:
            name: wrocc_adm
            rights: r--
    type: file
    version:
        branch: /main/porta_bas_052_maint
        name: lib_isps_annex_b.inc
        nr: '0'
        path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html/includes
-   comment: '"polish isps  {{dlv /dev_wro04012_porta_bas_052_maint/1}}  {{dlv /dev_wro_porta_bas_052_maint/1}}"'
    creator: Wiecek Pawel (wro02419.ClearCaseUsersWROI@wro2419c)
    datetime: '2008-07-14T15:34:36+02:00'
    elementtype: compressed_file
    labels:
    - PORTA_MAINT_BAS_052_011_313
    - PORTA_MAINT_BAS_052_011_312
    - PORTA_MAINT_BAS_052_011_311
    - PORTA_MAINT_BAS_052_010_501
    - PORTA_MAINT_BAS_052_011_310
    - PORTA_MAINT_BAS_052_010_850
    - PORTA_MAINT_BAS_052_011_302
    - PORTA_MAINT_BAS_052_010_850_T2
    - PORTA_MAINT_BAS_052_010_850_T1
    - PORTA_MAINT_BAS_052_011_301
    - PORTA_MAINT_BAS_052_010_844
    - PORTA_MAINT_BAS_052_011_300
    - PORTA_MAINT_BAS_052_011_300_T2
    - PORTA_MAINT_BAS_052_010_844_T2
    - PORTA_MAINT_BAS_052_011_300_T1
    - PORTA_MAINT_BAS_052_010_844_T1
    - PORTA_FRONTIER_BAS_000
    - PORTA_MAINT_BAS_052_010_843
    - PORTA_MAINT_BAS_052_010_842
    - PORTA_MAINT_BAS_052_010_842_T2
    - PORTA_MAINT_BAS_052_010_842_T1
    - PORTA_MAINT_BAS_052_010_800
    - PORTA_MAINT_BAS_052_010_700
    - PORTA_MAINT_BAS_052_010_600
    - PORTA_MAINT_BAS_052_010_500
    - PORTA_MAINT_BAS_052_011_200
    - PORTA_MAINT_BAS_052_010_400
    - PORTA_MAINT_BAS_052_011_100
    - PORTA_MAINT_BAS_052_010_300
    - PORTA_MAINT_BAS_052_011
    - PORTA_MAINT_BAS_052_011_T
    - PORTA_MAINT_BAS_052_010_200
    - PORTA_MAINT_BAS_052_010_100
    - PORTA_MAINT_BAS_052_010
    - PORTA_MAINT_BAS_052_010_T1
    - PORTA_MAINT_BAS_052_010_T
    predecessor:
        branch: /main/porta_bas_052_maint
        nr: '0'
    protection:
        group:
            name: PL_WRO_CC_USR
            rights: r--
        other:
            name: ''
            rights: r--
        user:
            name: wrocc_adm
            rights: r--
    type: file
    version:
        branch: /main/porta_bas_052_maint
        name: lib_isps_annex_b.inc
        nr: '1'
        path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html/includes
-   comment: ''
    creator: Pilka Dariusz (wro04030.ClearCaseUsersWROI@wro4030c)
    datetime: '2008-11-03T14:48:59+01:00'
    elementtype: compressed_file
    predecessor:
        branch: /main/porta_bas_052_maint
        nr: '1'
    protection:
        group:
            name: PL_WRO_CC_USR
            rights: r--
        other:
            name: ''
            rights: r--
        user:
            name: wrocc_adm
            rights: r--
    type: file
    version:
        branch: /main/porta_bas_052_maint/dev_wro_porta_bas_052_maint
        name: lib_isps_annex_b.inc
        nr: '0'
        path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html/includes
-   comment: '"caft 2607 issue 12  {{dlv /wro04030_porta_bas_052_maint/1}}"'
    creator: Pilka Dariusz (wro04030.ClearCaseUsersWROI@wro4030c)
    datetime: '2008-11-03T14:59:01+01:00'
    elementtype: compressed_file
    predecessor:
        branch: /main/porta_bas_052_maint/dev_wro_porta_bas_052_maint
        nr: '0'
    protection:
        group:
            name: PL_WRO_CC_USR
            rights: r--
        other:
            name: ''
            rights: r--
        user:
            name: wrocc_adm
            rights: r--
    type: file
    version:
        branch: /main/porta_bas_052_maint/dev_wro_porta_bas_052_maint
        name: lib_isps_annex_b.inc
        nr: '1'
        path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html/includes
-   comment: '"caft 2607 issue 10 small fix  {{dlv /wro04030_porta_bas_052_maint/2}}"'
    creator: Pilka Dariusz (wro04030.ClearCaseUsersWROI@wro4030c)
    datetime: '2008-11-04T12:44:14+01:00'
    elementtype: compressed_file
    predecessor:
        branch: /main/porta_bas_052_maint/dev_wro_porta_bas_052_maint
        nr: '1'
    protection:
        group:
            name: PL_WRO_CC_USR
            rights: r--
        other:
            name: ''
            rights: r--
        user:
            name: wrocc_adm
            rights: r--
    type: file
    version:
        branch: /main/porta_bas_052_maint/dev_wro_porta_bas_052_maint
        name: lib_isps_annex_b.inc
        nr: '2'
        path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html/includes
-   comment: '"caft 2607 issue 10  {{dlv /wro04030_porta_bas_052_maint/3}}"'
    creator: Pilka Dariusz (wro04030.ClearCaseUsersWROI@wro4030c)
    datetime: '2008-11-05T13:49:52+01:00'
    elementtype: compressed_file
    predecessor:
        branch: /main/porta_bas_052_maint/dev_wro_porta_bas_052_maint
        nr: '2'
    protection:
        group:
            name: PL_WRO_CC_USR
            rights: r--
        other:
            name: ''
            rights: r--
        user:
            name: wrocc_adm
            rights: r--
    type: file
    version:
        branch: /main/porta_bas_052_maint/dev_wro_porta_bas_052_maint
        name: lib_isps_annex_b.inc
        nr: '3'
        path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html/includes
-   comment: '"CR 2617  {{dlv /dev_wro04294_porta_bas_052_maint/1}}"'
    creator: Zlomek Krystian (wro04294.ClearCaseUsersWROI@wroe3549c)
    datetime: '2008-11-06T12:31:29+01:00'
    elementtype: compressed_file
    predecessor:
        branch: /main/porta_bas_052_maint/dev_wro_porta_bas_052_maint
        nr: '3'
    protection:
        group:
            name: PL_WRO_CC_USR
            rights: r--
        other:
            name: ''
            rights: r--
        user:
            name: wrocc_adm
            rights: r--
    type: file
    version:
        branch: /main/porta_bas_052_maint/dev_wro_porta_bas_052_maint
        name: lib_isps_annex_b.inc
        nr: '4'
        path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html/includes
-   comment: '"caft 2607 fast fix  {{dlv /wro04030_porta_bas_052_maint/4}}"'
    creator: Pilka Dariusz (wro04030.ClearCaseUsersWROI@wro4030c)
    datetime: '2008-11-07T15:21:46+01:00'
    elementtype: compressed_file
    predecessor:
        branch: /main/porta_bas_052_maint/dev_wro_porta_bas_052_maint
        nr: '4'
    protection:
        group:
            name: PL_WRO_CC_USR
            rights: r--
        other:
            name: ''
            rights: r--
        user:
            name: wrocc_adm
            rights: r--
    type: file
    version:
        branch: /main/porta_bas_052_maint/dev_wro_porta_bas_052_maint
        name: lib_isps_annex_b.inc
        nr: '5'
        path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html/includes
-   comment: "\"Rebased to PORTA_BAS_052_MAINT_DEV_WRO_04030  {{dlv /wro04030_porta_bas_052_maint/5}}\n\
        \   caft 2607 fast fix for frontier  {{dlv /wro04030_porta_bas_052_maint/6}}\""
    creator: Pilka Dariusz (wro04030.ClearCaseUsersWROI@wro4030c)
    datetime: '2008-11-24T10:15:30+01:00'
    elementtype: compressed_file
    labels:
    - PORTA_BAS_052_MAINT_DEV_WRO_02419
    - PORTA_BAS_052_MAINT_DEV_WRO_03037
    - PORTA_BAS_052_MAINT_DEV_WRO_e3727
    - PORTA_BAS_052_MAINT_DEV_WRO_04030
    - PORTA_BAS_052_MAINT_DEV_WRO_04122
    predecessor:
        branch: /main/porta_bas_052_maint/dev_wro_porta_bas_052_maint
        nr: '5'
    protection:
        group:
            name: PL_WRO_CC_USR
            rights: r--
        other:
            name: ''
            rights: r--
        user:
            name: wrocc_adm
            rights: r--
    type: file
    version:
        branch: /main/porta_bas_052_maint/dev_wro_porta_bas_052_maint
        name: lib_isps_annex_b.inc
        nr: '6'
        path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html/includes
-   comment: '"CAFT 2746"'
    creator: Zlomek Krystian (wro04294.ClearCaseUsersWROI@wroe3549c)
    datetime: '2009-02-27T12:25:07+01:00'
    elementtype: compressed_file
    labels:
    - skawinsk_m_ext
    - mocek_dari
    - MOCEK_DARI_PORTA_BAS_052_MAINT_SIB
    - WIECEK_PORTA_MAINT_52_PREINT_15AX
    - wiecek_paw
    - mandziej_z_ext
    - langiewi_m
    - kalinows_b
    - bielawsk_w
    - borowski_p
    - pilka_dari
    - zlomek_kry
    - zatorski_m
    - zarczyns_a
    - PORTA_BAS_052_MAINT_DEV_WRO_shc0036
    - PORTA_BAS_052_MAINT_DEV_WRO_04294
    - PORTA_BAS_052_MAINT_DEV_WRO_01565
    - PORTA_BAS_052_MAINT_DEV_WRO_01662
    - PORTA_BAS_052_MAINT_DEV_WRO_04012
    - PORTA_BAS_052_MAINT_DEV_WRO_shc0012
    - PORTA_BAS_052_MAINT_DEV_WRO_000
    predecessor:
        branch: /main/porta_bas_052_maint/dev_wro_porta_bas_052_maint
        nr: '6'
    protection:
        group:
            name: PL_WRO_CC_USR
            rights: r--
        other:
            name: ''
            rights: r--
        user:
            name: wrocc_adm
            rights: r--
    type: file
    version:
        branch: /main/porta_bas_052_maint/dev_wro_porta_bas_052_maint
        name: lib_isps_annex_b.inc
        nr: '7'
        path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html/includes
