


['2008-12-10T16:47:17+01:00', Wiecek Pawel (wro02419.ClearCaseUsersWROI@wro2419c),
  /home/langiewi_m/p2_latest/develop/source/siemens/applications/html, Makefile, /main/dev_wro_porta_bas_052_maint,
  '1']


comment: '"Import changed Makefile from rel3.  {{dlv /dev_wro02419_porta_bas_052_maint/1}}"'
creator: Wiecek Pawel (wro02419.ClearCaseUsersWROI@wro2419c)
datetime: '2008-12-10T16:47:17+01:00'
elementtype: text_file
hyperlinks:
- {link: /vobs/porta -> /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/porta_bas_052_maint/1,
  nr: '119917', type: Merge}
- {link: /vobs/porta <- /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/dev_wro02419_porta_bas_052_maint/1,
  nr: '119838', type: Merge}
labels: [skawinsk_m_ext, mocek_dari, MOCEK_DARI_PORTA_BAS_052_MAINT_SIB, WIECEK_PORTA_MAINT_52_PREINT_15AX,
  wiecek_paw, mandziej_z_ext, langiewi_m, kalinows_b, bielawsk_w, borowski_p, pilka_dari,
  zlomek_kry, zatorski_m, zarczyns_a, PORTA_BAS_052_MAINT_DEV_WRO_03037, PORTA_BAS_052_MAINT_DEV_WRO_04012,
  PORTA_BAS_052_MAINT_DEV_WRO_shc0036, PORTA_BAS_052_MAINT_DEV_WRO_04030, PORTA_BAS_052_MAINT_DEV_WRO_01662,
  PORTA_BAS_052_MAINT_DEV_WRO_shc0012, PORTA_BAS_052_MAINT_DEV_WRO_01565, PORTA_BAS_052_MAINT_DEV_WRO_04294,
  PORTA_BAS_052_MAINT_DEV_WRO_02419, PORTA_BAS_052_MAINT_DEV_WRO_04122, PORTA_BAS_052_MAINT_DEV_WRO_000]
predecessor: {branch: /main/dev_wro_porta_bas_052_maint, nr: '0'}
protection:
  group: {name: PL_WRO_CC_USR, rights: r--}
  other: {name: '', rights: r--}
  user: {name: wrocc_adm, rights: r--}
type: file
version: {branch: /main/dev_wro_porta_bas_052_maint, name: Makefile, nr: '1', path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html}



['2008-12-10T16:33:54+01:00', Wiecek Pawel (wro02419.ClearCaseUsersWROI@wro2419c),
  /home/langiewi_m/p2_latest/develop/source/siemens/applications/html, Makefile, /main/dev_wro_porta_bas_052_maint,
  '0']


comment: ''
creator: Wiecek Pawel (wro02419.ClearCaseUsersWROI@wro2419c)
datetime: '2008-12-10T16:33:54+01:00'
elementtype: text_file
predecessor: {branch: /main, nr: '16'}
protection:
  group: {name: PL_WRO_CC_USR, rights: r--}
  other: {name: '', rights: r--}
  user: {name: wrocc_adm, rights: r--}
type: file
version: {branch: /main/dev_wro_porta_bas_052_maint, name: Makefile, nr: '0', path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html}



['2007-10-11T12:12:14+02:00', Wiecek Pawel (wro02419.ClearCaseUsersWROI@wro2419c),
  /home/langiewi_m/p2_latest/develop/source/siemens/applications/html, Makefile, /main,
  '16']


comment: '"Create scripts/filesystem_data  {{dlv /dev_wro02419_porta/7}}  {{dlv /dev_wro_porta/7}}"'
creator: Wiecek Pawel (wro02419.ClearCaseUsersWROI@wro2419c)
datetime: '2007-10-11T12:12:14+02:00'
elementtype: text_file
hyperlinks:
- {link: /vobs/porta -> /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/dev_jr_porta/9,
  nr: '60258', type: Merge}
- {link: /vobs/porta -> /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/dev_brq_porta/2,
  nr: '60575', type: Merge}
- {link: /vobs/porta -> /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/porta_wimax/2,
  nr: '72235', type: Merge}
- {link: /vobs/porta <- /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/dev_wro_porta/7,
  nr: '59237', type: Merge}
labels: [PORTA_MAINT_BAS_052_011_313, PORTA_MAINT_BAS_052_011_312, PORTA_MAINT_BAS_052_011_311,
  PORTA_MAINT_BAS_052_010_501, PORTA_MAINT_BAS_052_002_001, PORTA_MAINT_BAS_052_011_310,
  PORTA_MAINT_BAS_052_002_101, PORTA_MAINT_BAS_052_010_850, PORTA_MAINT_BAS_052_011_302,
  PORTA_MAINT_BAS_052_010_850_T2, PORTA_MAINT_BAS_052_010_850_T1, PORTA_FRONTIER_BAS_052_011_310_T6,
  PORTA_FRONTIER_BAS_052_011_310_T5, PORTA_FRONTIER_BAS_052_011_310_T4, PORTA_MAINT_BAS_052_011_301,
  PORTA_FRONTIER_BAS_052_011_310, PORTA_MAINT_BAS_052_011_309, PORTA_MAINT_BAS_052_010_844,
  PORTA_MAINT_BAS_052_011_300, PORTA_MAINT_BAS_052_011_300_T2, PORTA_MAINT_BAS_052_010_844_T2,
  PORTA_MAINT_BAS_052_011_300_T1, PORTA_MAINT_BAS_052_010_844_T1, PORTA_FRONTIER_BAS_000,
  PORTA_MAINT_BAS_052_010_843, PORTA_MAINT_BAS_052_010_842, PORTA_MAINT_BAS_052_010_842_T2,
  PORTA_MAINT_BAS_052_010_842_T1, PORTA_MAINT_BAS_052_010_800, PORTA_MAINT_BAS_052_010_700,
  PORTA_MAINT_BAS_052_010_600, PORTA_MAINT_BAS_052_010_500, PORTA_MAINT_BAS_052_011_200,
  PORTA_MAINT_BAS_052_010_400, PORTA_MAINT_BAS_052_011_100, PORTA_MAINT_BAS_052_010_300,
  PORTA_MAINT_BAS_052_011, PORTA_MAINT_BAS_052_011_T, PORTA_MAINT_BAS_052_010_200,
  PORTA_MAINT_BAS_052_010_100, PORTA_MAINT_BAS_052_010, PORTA_MAINT_BAS_052_009, PORTA_MAINT_BAS_052_010_T1,
  PORTA_MAINT_BAS_052_010_T, PORTA_MAINT_BAS_052_006_310, PORTA_MAINT_BAS_052_009_T,
  PORTA_MAINT_BAS_052_008, PORTA_MAINT_BAS_052_008_T2, PORTA_MAINT_BAS_052_008_T1,
  PORTA_MAINT_BAS_052_008_T, PORTA_MAINT_BAS_052_006_300, PORTA_MAINT_BAS_052_002_200,
  PORTA_MAINT_BAS_052_002_200_T, PORTA_MAINT_BAS_052_007, PORTA_MAINT_BAS_052_007_T1,
  PORTA_MAINT_BAS_052_006_200, PORTA_MAINT_BAS_052_007_T, PORTA_MAINT_BAS_052_006_T100,
  PORTA_MAINT_BAS_052_006, PORTA_MAINT_BAS_052_006_T, PORTA_MAINT_BAS_052_005, PORTA_MAINT_BAS_052_005_T1,
  PORTA_MAINT_BAS_052_005_T, PORTA_2_0_BAS_052_013, PORTA_2_0_BAS_052_012, PORTA_MAINT_BAS_052_004,
  PORTA_MAINT_BAS_052_004_T1, PORTA_MAINT_BAS_052_004_T, PORTA_2_0_BAS_052_011, PORTA_MAINT_BAS_052_003_100,
  PORTA_2_0_BAS_052_010, PORTA_MAINT_BAS_052_003_100_T, PORTA_2_0_BAS_052_009, PORTA_2_0_BAS_049.01_008,
  PORTA_MAINT_BAS_052_003, PORTA_MAINT_BAS_052_003_T3, PORTA_MAINT_BAS_052_003_T2,
  _PORTA_MAINT_BAS_052_003_T1, PORTA_MAINT_BAS_052_002_100, PORTA_2_0_BAS_049.01_007,
  PORTA_MAINT_BAS_052_003_T, PORTA_2_0_BAS_049.01_006, PORTA_MAINT_BAS_052_002, PORTA_TDC_BAS_051_009,
  PORTA_2_0_BAS_049.01_005, PORTA_MAINT_BAS_052_001, PORTA_BAS_049_8, PORTA_MAINT_BAS_052_000,
  PORTA_BAS_052_1, PORTA_BAS_049_7, PORTA_BAS_052, PORTA_2_0_BAS_049.01_004, PORTA_TDC_BAS_051_008,
  PORTA_BAS_051_1, PORTA_BAS_052_T2, PORTA_TDC_BAS_051_007, PORTA_BAS_052_T1, PORTA_TDC_BAS_051_007_T,
  PORTA_BAS_052_T, PORTA_PGW_OSGI_BAS_051_005, PORTA_BAS_051, PORTA_2_0_BAS_049.01_003,
  PORTA_BAS_051_T2, PORTA_BAS_049_6, PORTA_BAS_051_T1, PORTA_BAS_051_T, PORTA_BAS_050_1_100,
  PORTA_BAS_050_1, PORTA_BAS_049_5, PORTA_PGW_OSGI_BAS_050_004, PORTA_PGW_OSGI_BAS_050_004_T1,
  PORTA_TDC_BAS_050_006, PORTA_TDC_BAS_050_006_T, PORTA_PGW_OSGI_BAS_050_004_T, PORTA_BAS_049_4_100,
  PORTA_BAS_049_4, PORTA_BAS_050, PORTA_BAS_050_T2, PORTA_BAS_049_3, PORTA_PGW_OSGI_BAS_049_003,
  PORTA_BAS_049_2, PORTA_BAS_050_T1, PORTA_BAS_050_T, PORTA_PGW_OSGI_BAS_049_003_T1,
  PORTA_2_0_BAS_049.01_002, PORTA_PGW_OSGI_BAS_049_003_T, PORTA_BAS_049_1, PORTA_BAS_049,
  PORTA_BAS_049_T2, PORTA_BAS_049_T1, PORTA_BAS_049_T, PORTA_TDC_BAS_048_005, PORTA_TDC_BAS_048_005_T1,
  PORTA_TDC_BAS_048_005_T, PORTA_BAS_048_1, PORTA_BAS_047_NEW_BOOTLOADER, PORTA_BAS_048,
  PORTA_BAS_048_T1, PORTA_BAS_048_T, PORTA_TDC_BAS_047_004, PORTA_TDC_BAS_047_004_T1,
  PORTA_TDC_BAS_047_004_T, PORTA_2_0_BAS_047_001, PORTA_BAS_047, PORTA_BAS_047_T2,
  PORTA_BAS_047_T1, PORTA_BAS_047_T, PORTA_PGW_OSGI_BAS_046_002, PORTA_TDC_BAS_046_003,
  PORTA_TDC_BAS_046_003_T1, PORTA_BAS_046_1, PORTA_TDC_BAS_046_003_T, PORTA_BAS_046,
  PORTA_BAS_046_T2, PORTA_BAS_046_T1, PORTA_BAS_046_T]
predecessor: {branch: /main, nr: '15'}
protection:
  group: {name: PL_WRO_CC_USR, rights: r--}
  other: {name: '', rights: r--}
  user: {name: wrocc_adm, rights: r--}
type: file
version: {branch: /main, name: Makefile, nr: '16', path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html}



['2007-08-27T15:37:00+02:00', Wiecek Pawel (wro02419.ClearCaseUsersWROI@wro2419c),
  /home/langiewi_m/p2_latest/develop/source/siemens/applications/html, Makefile, /main,
  '15']


comment: '"strip .css files as well  {{dlv /dev_wro02419_porta/6}}  {{dlv /dev_wro_porta/6}}"'
creator: Wiecek Pawel (wro02419.ClearCaseUsersWROI@wro2419c)
datetime: '2007-08-27T15:37:00+02:00'
elementtype: text_file
hyperlinks:
- {link: /vobs/porta -> /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/dev_brq_porta/1,
  nr: '56037', type: Merge}
- {link: /vobs/porta -> /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/dev_jr_porta/8,
  nr: '56826', type: Merge}
- {link: /vobs/porta <- /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/dev_wro_porta/6,
  nr: '53016', type: Merge}
labels: [PORTA_WIMAX_BAS_044_004_T3, PORTA_WIMAX_BAS_044_004, PORTA_WIMAX_BAS_044_004_T2,
  PORTA_WIMAX_BAS_044_004_T1, PORTA_WIMAX_BAS_044_004_T, PORTA_WIMAX_BAS_044_003,
  PORTA_WIMAX_BAS_044_003_T1, PORTA_WIMAX_BAS_044_003_T, PORTA_WIMAX_BAS_044_002,
  PORTA_WIMAX_BAS_044_001, PORTA_WIMAX_BAS_002_T, PORTA_BAS_045_1, PORTA_BAS_045_1_T,
  PORTA_PGW_OSGI_BAS_045_001, PORTA_PGW_OSGI_BAS_045_001_T, PORTA_BAS_045, PORTA_WIMAX_BAS_044_000,
  PORTA_BAS_045_T2, PORTA_PGW_OSGI_BAS_045_T1_001, PORTA_BAS_045_T1, PORTA_BAS_045_T,
  PORTA_PGW_OSGI_BAS_044_000, PORTA_2_0_BAS_044_000, PORTA_TDC_BAS_044_002, PORTA_TDC_BAS_044_002_T1,
  PORTA_TDC_BAS_044_002_T, PORTA_BAS_044, PORTA_BAS_044_T3, PORTA_BAS_044_TX, PORTA_BAS_044_T2,
  PORTA_BAS_044_T1, PORTA_BAS_044_T]
predecessor: {branch: /main, nr: '14'}
protection:
  group: {name: PL_WRO_CC_USR, rights: r--}
  other: {name: '', rights: r--}
  user: {name: wrocc_adm, rights: r--}
type: file
version: {branch: /main, name: Makefile, nr: '15', path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html}



['2007-08-13T13:38:38+02:00', Szurgot Bartosz (wro03609.ClearCaseUsersWROI@wroe1285c),
  /home/langiewi_m/p2_latest/develop/source/siemens/applications/html, Makefile, /main,
  '14']


comment: '"#723: install scm*init files in debug profiles  {{dlv /dev_wro02419_porta/5}}  {{dlv
  /dev_wro_porta/5}}"'
creator: Szurgot Bartosz (wro03609.ClearCaseUsersWROI@wroe1285c)
datetime: '2007-08-13T13:38:38+02:00'
elementtype: text_file
hyperlinks:
- {link: /vobs/porta -> /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/dev_jr_porta/7,
  nr: '52603', type: Merge}
- {link: /vobs/porta <- /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/dev_wro_porta/5,
  nr: '50908', type: Merge}
labels: [PORTA_PPFORM_BAS_043_2_001, PORTA_BAS_043_2, PORTA_BAS_043_1, PORTA_BAS_043,
  PORTA_BAS_043_T2, PORTA_BAS_043_T1, PORTA_BAS_043_T]
predecessor: {branch: /main, nr: '13'}
protection:
  group: {name: PL_WRO_CC_USR, rights: r--}
  other: {name: '', rights: r--}
  user: {name: wrocc_adm, rights: r--}
type: file
version: {branch: /main, name: Makefile, nr: '14', path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html}



['2007-08-01T13:38:53+02:00', Szurgot Bartosz (wro03609.ClearCaseUsersWROI@wroe1285c),
  /home/langiewi_m/p2_latest/develop/source/siemens/applications/html, Makefile, /main,
  '13']


comment: "\"Don't install trash  {{dlv /dev_wro02419_porta/3}}  {{dlv /dev_wro_porta/4}}\n\
  \   Damn the broken install  {{dlv /dev_wro02419_porta/4}}  {{dlv /dev_wro_porta/4}}\""
creator: Szurgot Bartosz (wro03609.ClearCaseUsersWROI@wroe1285c)
datetime: '2007-08-01T13:38:53+02:00'
elementtype: text_file
hyperlinks:
- {link: /vobs/porta -> /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/dev_jr_porta/6,
  nr: '50894', type: Merge}
- {link: /vobs/porta <- /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/dev_wro_porta/4,
  nr: '49159', type: Merge}
labels: [PORTA_ATT2_BAS_011_T4, PORTA_ATT2_BAS_011_T3, PORTA_TDC_BAS_042_001_100,
  PORTA_TDC_BAS_042_001_100_T, PORTA_ATT2_BAS_011_T2, PORTA_ATT2_BAS_011_T1, PORTA_ATT2_BAS_011_T,
  PORTA_TDC_BAS_042_001, PORTA_TDC_BAS_042_001_T2, PORTA_TDC_BAS_042_001_T1, PORTA_TDC_BAS_042_001_T,
  PORTA_BAS_042_1, PORTA_BAS_042, PORTA_BAS_042_T1, PORTA_BAS_042_T]
predecessor: {branch: /main, nr: '12'}
protection:
  group: {name: PL_WRO_CC_USR, rights: r--}
  other: {name: '', rights: r--}
  user: {name: wrocc_adm, rights: r--}
type: file
version: {branch: /main, name: Makefile, nr: '13', path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html}



['2007-07-13T15:55:02+02:00', Wiecek Pawel (wro02419.ClearCaseUsersWROI@wro2419c),
  /home/langiewi_m/p2_latest/develop/source/siemens/applications/html, Makefile, /main,
  '12']


comment: "\"Install for native profile as well...  {{dlv /dev_wro02419_porta/1}} \
  \ {{dlv /dev_wro_porta/2}}\n   Install tests for native  {{dlv /dev_wro02419_porta/2}}\
  \  {{dlv /dev_wro_porta/3}}\""
creator: Wiecek Pawel (wro02419.ClearCaseUsersWROI@wro2419c)
datetime: '2007-07-13T15:55:02+02:00'
elementtype: text_file
hyperlinks:
- {link: /vobs/porta -> /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/dev_jr_porta/5,
  nr: '48111', type: Merge}
- {link: /vobs/porta <- /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/dev_wro_porta/3,
  nr: '47343', type: Merge}
labels: [PORTA_ATT2_BAS_010, PORTA_ATT2_BAS_010_T2, PORTA_ATT2_BAS_010_T1, PORTA_ATT2_BAS_010_T,
  PORTA_TDC_BAS_041_001, PORTA_TDC_BAS_041_001_T1, PORTA_TDC_BAS_041_001_T, PORTA_BAS_041,
  PORTA_BAS_041_T2, PORTA_BAS_041_T1, PORTA_BAS_041_T]
predecessor: {branch: /main, nr: '11'}
protection:
  group: {name: PL_WRO_CC_USR, rights: r--}
  other: {name: '', rights: r--}
  user: {name: wrocc_adm, rights: r--}
type: file
version: {branch: /main, name: Makefile, nr: '12', path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html}



['2007-06-26T15:01:16+02:00', Wiecek Pawel (wro02419.ClearCaseUsersWROI@wro2419c),
  /home/langiewi_m/p2_latest/develop/source/siemens/applications/html, Makefile, /main,
  '11']


comment: '"Optimize footprint  {{dlv /dev_wro_porta/1}}"'
creator: Wiecek Pawel (wro02419.ClearCaseUsersWROI@wro2419c)
datetime: '2007-06-26T15:01:16+02:00'
elementtype: text_file
hyperlinks:
- {link: /vobs/porta -> /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/dev_jr_porta/4,
  nr: '46729', type: Merge}
- {link: /vobs/porta <- /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/dev_wro_porta/1,
  nr: '45966', type: Merge}
labels: [PORTA_ATT2_BAS_009_ZB, PORTA_ATT2_BAS_009, PORTA_ATT2_BAS_009_T2, PORTA_ATT2_BAS_009_T1,
  PORTA_TDC_BAS_040_001_T1, PORTA_ATT2_BAS_009_T, PORTA_TDC_BAS_040_001_PRE_01, PORTA_TDC_BAS_040_001_T,
  PORTA_BAS_040, PORTA_BAS_040_T2, PORTA_BAS_040_T1, PORTA_BAS_040_T]
predecessor: {branch: /main, nr: '10'}
protection:
  group: {name: PL_WRO_CC_USR, rights: r--}
  other: {name: '', rights: r--}
  user: {name: wrocc_adm, rights: r--}
type: file
version: {branch: /main, name: Makefile, nr: '11', path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html}



['2007-03-30T12:56:05+02:00', Michael Bennemann (mbn.ccusers@bchk081x), /home/langiewi_m/p2_latest/develop/source/siemens/applications/html,
  Makefile, /main, '10']


comment: '"Merge from PORTA_V2_BAS_034_T1"'
creator: Michael Bennemann (mbn.ccusers@bchk081x)
datetime: '2007-03-30T12:56:05+02:00'
elementtype: text_file
hyperlinks:
- {link: /vobs/porta -> /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/dev_jr_porta/3,
  nr: '37521', type: Merge}
- {link: /vobs/porta <- /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/porta_v2/2,
  nr: '36927', type: Merge}
labels: [PORTA_ATT2_BAS_008.01, PORTA_ATT2_BAS_008, PORTA_ATT2_BAS_008_T3, PORTA_TDC_BAS_039_000,
  PORTA_ATT2_BAS_008_T2, PORTA_ATT2_BAS_008_T1, PORTA_ATT2_BAS_008_T, PORTA_ATT2_BAS_007,
  PORTA_ATT2_BAS_007_T3, PORTA_ATT2_BAS_007_T2, PORTA_ATT2_BAS_007_T, PORTA_BAS_039,
  PORTA_BAS_039_T2, PORTA_BAS_039_T1, PORTA_BAS_039_T, PORTA_ATT2_BAS_006, PORTA_ATT2_BAS_006_T2,
  PORTA_ATT2_BAS_006_T1, PORTA_ATT2_BAS_006_T, PORTA_BAS_038, PORTA_BAS_038_T3, PORTA_BAS_038_T2,
  PORTA_BAS_038_T1, PORTA_ATT2_BAS_005, PORTA_ATT2_BAS_005_T3, PORTA_ATT2_BAS_005_T2,
  PORTA_BAS_038_T, PORTA_ATT2_BAS_005_T1, PORTA_BAS_037, PORTA_ATT2_BAS_005_T, PORTA_BAS_037_T1,
  PORTA_BAS_037_T, PORTA_BAS_036, PORTA_BAS_036_T1, PORTA_BAS_036_T, PORTA_BAS_035]
predecessor: {branch: /main, nr: '9'}
protection:
  group: {name: PL_WRO_CC_USR, rights: r--}
  other: {name: '', rights: r--}
  user: {name: wrocc_adm, rights: r--}
type: file
version: {branch: /main, name: Makefile, nr: '10', path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html}



['2007-02-13T12:42:24+01:00', Libor Svehlak (svehlakl.gs_herkules@leonardo.brqhe.anfdata.cz),
  /home/langiewi_m/p2_latest/develop/source/siemens/applications/html, Makefile, /main,
  '9']


comment: '"Changed paths"'
creator: Libor Svehlak (svehlakl.gs_herkules@leonardo.brqhe.anfdata.cz)
datetime: '2007-02-13T12:42:24+01:00'
elementtype: text_file
hyperlinks:
- {link: /vobs/porta -> /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/dev_brno_porta_v2/1,
  nr: '30381', type: Merge}
- {link: /vobs/porta -> /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/porta_v2/1,
  nr: '30428', type: Merge}
labels: [PORTA_MAINT_BAS_034_010_600, PORTA_MAINT_BAS_034_010_500, PORTA_MAINT_BAS_034_010_400,
  PORTA_MAINT_BAS_034_010_300, PORTA_MAINT_BAS_034_010_300_T1, PORTA_MAINT_BAS_034_010_300_T,
  PORTA_MAINT_BAS_034_010_200, PORTA_MAINT_BAS_034_010_100, PORTA_MAINT_BAS_034_010,
  PORTA_MAINT_BAS_034_010_T2, PORTA_MAINT_BAS_034_010_T1, PORTA_MAINT_BAS_034_010_T,
  PORTA_MAINT_BAS_034_007_100, PORTA_MAINT_BAS_034_009_100, PORTA_MAINT_BAS_034_009,
  PORTA_MAINT_BAS_034_009_T1, PORTA_MAINT_BAS_034_009_T, PORTA_MAINT_BAS_034_008_100,
  PORTA_MAINT_BAS_034_008, PORTA_MAINT_BAS_034_008_T1, PORTA_MAINT_BAS_034_008_T,
  PORTA_MAINT_BAS_034_007, PORTA_MAINT_BAS_034_007_T2, PORTA_MAINT_BAS_034_007_T1,
  PORTA_MAINT_BAS_034_007_T, PORTA_MAINT_BAS_034_006, PORTA_MAINT_BAS_034_006_T2,
  PORTA_MAINT_BAS_034_006_T1, PORTA_MAINT_BAS_034_006_T, PORTA_MAINT_BAS_034_005,
  PORTA_MAINT_BAS_034_005_T1, PORTA_MAINT_BAS_034_005_T, PORTA_MAINT_BAS_034_004,
  PORTA_MAINT_BAS_034_004_T2, PORTA_MAINT_BAS_034_004_T1, PORTA_W502V_BAS_034_003_T1,
  PORTA_MAINT_BAS_034_004_T, PORTA_MAINT_BAS_034_003, PORTA_MAINT_BAS_034_003_T3,
  PORTA_MAINT_BAS_034_003_T2, PORTA_MAINT_BAS_034_003_T1, PORTA_MAINT_BAS_034_003_T,
  PORTA_MAINT_BAS_034_002, PORTA_W502V_BAS_034_002, PORTA_W502V_BAS_034_002_T, PORTA_MAINT_BAS_034_001,
  PORTA_ATT2_BAS_004, PORTA_W502V_BAS_034_001, PORTA_MAINT_BAS_034_000, PORTA_BAS_034,
  PORTA_BAS_034_T4, PORTA_BAS_034_T3, PORTA_BAS_034_T2, PORTA_BAS_034_T1, PORTA_BAS_034_T,
  PORTA_BAS_033_2, PORTA_BAS_033_1, PORTA_ATT2_BAS_003, PORTA_ATT2_BAS_002, PORTA_W502V_BAS_000,
  PORTA_BAS_033, PORTA_BAS_033_T2, PORTA_BAS_033_T1, PORTA_BAS_033_T, PORTA_BAS_032_1,
  PORTA_BAS_032_1_T]
predecessor: {branch: /main, nr: '8'}
protection:
  group: {name: PL_WRO_CC_USR, rights: r--}
  other: {name: '', rights: r--}
  user: {name: wrocc_adm, rights: r--}
type: file
version: {branch: /main, name: Makefile, nr: '9', path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html}



['2007-01-16T15:43:37+01:00', Ales Holec (holeca.gs_herkules@leonardo.brqhe.anfdata.cz),
  /home/langiewi_m/p2_latest/develop/source/siemens/applications/html, Makefile, /main,
  '8']


comment: ''
creator: Ales Holec (holeca.gs_herkules@leonardo.brqhe.anfdata.cz)
datetime: '2007-01-16T15:43:37+01:00'
elementtype: text_file
hyperlinks:
- {link: /vobs/porta <- /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/dev_brno_porta/16,
  nr: '22314', type: Merge}
labels: [PORTA_PGW_BAS_007, PORTA_PGW_BAS_006, PORTA_PGW_BAS_006_T, PORTA_PGW_BAS_005,
  PORTA_PGW_BAS_005_T, PORTA_PGW_BAS_004, PORTA_PGW_BAS_004_T, PORTA_PGW_BAS_003,
  PORTA_PGW_BAS_003_T, PORTA_V2_BAS_032_T, PORTA_PGW_BAS_002, PORTA_ATT2_BAS_001,
  PORTA_PGW_BAS_002_T, PORTA_V2_BAS_001_T, PORTA_ATT2_BAS_000, PORTA_V2_BAS_000, PORTA_BAS_032,
  PORTA_BAS_032_T1, PORTA_BAS_032_T, PORTA_BAS_031, PORTA_BAS_031_T2, PORTA_BAS_031_T,
  PORTA_DANUBE_BAS_013, PORTA_BAS_031_T1, PORTA_DANUBE_BAS_013_T, PORTA_DANUBE_BAS_013_T2,
  PORTA_DANUBE_BAS_013_T1, PORTA_BAS_030, PORTA_BAS_030_T3, PORTA_BAS_030_T2, PORTA_BAS_030_T1,
  PORTA_BAS_030_T]
predecessor: {branch: /main, nr: '7'}
protection:
  group: {name: PL_WRO_CC_USR, rights: r--}
  other: {name: '', rights: r--}
  user: {name: wrocc_adm, rights: r--}
type: file
version: {branch: /main, name: Makefile, nr: '8', path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html}



['2006-11-27T17:40:05+01:00', Ales Holec (holeca.gs_herkules@leonardo.brqhe.anfdata.cz),
  /home/langiewi_m/p2_latest/develop/source/siemens/applications/html, Makefile, /main,
  '7']


comment: '"Merged from Brno"'
creator: Ales Holec (holeca.gs_herkules@leonardo.brqhe.anfdata.cz)
datetime: '2006-11-27T17:40:05+01:00'
elementtype: text_file
hyperlinks:
- {link: /vobs/porta -> /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/dev_brno_porta_thus/1,
  nr: '14362', type: Merge}
- {link: /vobs/porta -> /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/porta_v1_kpn/3,
  nr: '14562', type: Merge}
- {link: /vobs/porta -> /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/porta_v2_pre/2,
  nr: '16217', type: Merge}
- {link: /vobs/porta <- /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/dev_brno_porta/11,
  nr: '13904', type: Merge}
labels: [PORTA_V1_MAINT_BAS_029_3, PORTA_V1_MAINT_BAS_029_3_T2, PORTA_V1_MAINT_BAS_029_3_T1,
  PORTA_V1_MAINT_BAS_029_3_T, PORTA_V1_MAINT_BAS_029_2, PORTA_V1_MAINT_BAS_029_2_T2,
  PORTA_V1_MAINT_BAS_029_2_T1, PORTA_V1_MAINT_BAS_029_2_T, PORTA_PGW_BAS_001, PORTA_ATT_BAS_001,
  PORTA_PGW_BAS_000, PORTA_V1_MAINT_BAS_029_1, PORTA_V1_MAINT_BAS_029_1_T3, PORTA_DANUBE_BAS_012,
  PORTA_DANUBE_BAS_012_T2, PORTA_V1_MAINT_BAS_029_1_T2, PORTA_DANUBE_BAS_012_T1, PORTA_DANUBE_BAS_012_T,
  PORTA_V1_MAINT_BAS_029_1_T1, PORTA_V1_MAINT_BAS_029_1_T, prj, PORTA_ATT_BAS_000,
  PORTA_V1_THUS_BAS_029, PORTA_V1_THUS_BAS_029_T2, PORTA_V1_THUS_BAS_029_T1, PORTA_DANUBE_BAS_011_1,
  PORTA_DANUBE_BAS_011, PORTA_DANUBE_BAS_011_T1, PORTA_DANUBE_BAS_011_T, PORTA_V1_MAINT_BAS_029_0,
  PORTA_DANUBE_BAS_010, PORTA_V1_THUS_BAS_029_T, PORTA_BAS_029, PORTA_DANUBE_BAS_009,
  PORTA_BAS_029_T3, PORTA_DANUBE_BAS_009_T, PORTA_BAS_029_T2, PORTA_BAS_029_T1, PORTA_BAS_029_T,
  PORTA_DANUBE_BAS_008, PORTA_DANUBE_BAS_007, PORTA_DANUBE_BAS_007_T1, PORTA_DANUBE_BAS_007_T,
  PORTA_V1_THUS_BAS_000, PORTA_BAS_028, PORTA_BAS_028_T3, PORTA_BAS_028_T2, PORTA_BAS_028_T1,
  PORTA_BAS_028_T]
predecessor: {branch: /main, nr: '6'}
protection:
  group: {name: PL_WRO_CC_USR, rights: r--}
  other: {name: '', rights: r--}
  user: {name: wrocc_adm, rights: r--}
type: file
version: {branch: /main, name: Makefile, nr: '7', path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html}



['2006-08-07T17:10:17+02:00', Ales Holec (holeca.gs_herkules@cz2cb8dc), /home/langiewi_m/p2_latest/develop/source/siemens/applications/html,
  Makefile, /main, '6']


comment: '"Merged from BRNO_PORTA_BAS_021_FREEZE"'
creator: Ales Holec (holeca.gs_herkules@cz2cb8dc)
datetime: '2006-08-07T17:10:17+02:00'
elementtype: text_file
hyperlinks:
- {link: /vobs/porta -> /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/porta_v1_kpn/2,
  nr: '3920', type: Merge}
- {link: /vobs/porta -> /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/porta_v2_pre/1,
  nr: '5468', type: Merge}
- {link: /vobs/porta <- /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/dev_brno_porta/9,
  nr: '1608', type: Merge}
labels: [PORTA_DANUBE_BAS_006, PORTA_DANUBE_BAS_006_T2, PORTA_DANUBE_BAS_006_T1, PORTA_DANUBE_BAS_006_T,
  PORTA_DANUBE_BAS_005, PORTA_DANUBE_BAS_005_T6, PORTA_DANUBE_BAS_005_T5, PORTA_DANUBE_BAS_005_T4,
  PORTA_DANUBE_BAS_005_T3, PORTA_DANUBE_BAS_005_T, PORTA_DANUBE_BAS_005_T2, PORTA_BAS_027,
  PORTA_BAS_027_T6, PORTA_BAS_027_T5, PORTA_DANUBE_BAS_005_T1, PORTA_BAS_027_T4, PORTA_BAS_027_T3,
  PORTA_BAS_027_T2, PORTA_BAS_027_T1, PORTA_BAS_027_T, PORTA_DANUBE_BAS_004, PORTA_DANUBE_BAS_004_T2,
  PORTA_DANUBE_BAS_004_T1, PORTA_BAS_026, PORTA_BAS_026_T3, PORTA_DANUBE_BAS_004_T0,
  PORTA_DANUBE_BAS_003_SYNC_001, PORTA_TIH_BAS_025, PORTA_BAS_026_T2, PORTA_TIH_BAS_025_T,
  PORTA_BAS_026_T1, PORTA_DANUBE_BAS_003, PORTA_BAS_026_T, PORTA_BAS_025_2, PORTA_BAS_025_1,
  PORTA_BAS_025, PORTA_BAS_025_T3, PORTA_DANUBE_BAS_002, PORTA_BAS_025_T2, PORTA_BAS_025_T1,
  PORTA_BAS_025_T, PORTA_DANUBE_BAS_001, PORTA_DANUBE_BAS_000, PORTA_BAS_024_T3, PORTA_BAS_024,
  PORTA_TIH_BAS_023, PORTA_BAS_024_T2, PORTA_BAS_024_T1, PORTA_BAS_024_T, PORTA_TIH_BAS_023_T,
  PORTA_BAS_023, PORTA_BAS_023_T2, PORTA_BAS_023_T1, PORTA_BAS_023_T, PORTA_TIH_BAS_021,
  PORTA_BAS_022, PORTA_BAS_022_T3, PORTA_BAS_022_T2, PORTA_BAS_022_T1, PORTA_BAS_022_T,
  PORTA_TIH_BAS_021_T, PORTA_BAS_021_1, PORTA_BAS_021, PORTA_BAS_021_T3, PORTA_BAS_021_T2,
  PORTA_BAS_021_T1, PORTA_BAS_021_T]
predecessor: {branch: /main, nr: '5'}
protection:
  group: {name: PL_WRO_CC_USR, rights: r--}
  other: {name: '', rights: r--}
  user: {name: wrocc_adm, rights: r--}
type: file
version: {branch: /main, name: Makefile, nr: '6', path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html}



['2006-08-02T16:32:24+02:00', Libor Svehlak (svehlakl.gs_herkules@cz2cba7c_linux),
  /home/langiewi_m/p2_latest/develop/source/siemens/applications/html, Makefile, /main,
  '5']


comment: ''
creator: Libor Svehlak (svehlakl.gs_herkules@cz2cba7c_linux)
datetime: '2006-08-02T16:32:24+02:00'
elementtype: text_file
hyperlinks:
- {link: /vobs/porta -> /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/porta_v1_kpn/1,
  nr: '1172', type: Merge}
- {link: /vobs/porta <- /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/dev_brno_porta/6,
  nr: '1167', type: Merge}
predecessor: {branch: /main, nr: '4'}
protection:
  group: {name: PL_WRO_CC_USR, rights: r--}
  other: {name: '', rights: r--}
  user: {name: wrocc_adm, rights: r--}
type: file
version: {branch: /main, name: Makefile, nr: '5', path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html}



['2006-08-02T13:46:02+02:00', Libor Svehlak (svehlakl.gs_herkules@cz2cba7c_linux),
  /home/langiewi_m/p2_latest/develop/source/siemens/applications/html, Makefile, /main,
  '4']


comment: ''
creator: Libor Svehlak (svehlakl.gs_herkules@cz2cba7c_linux)
datetime: '2006-08-02T13:46:02+02:00'
elementtype: text_file
hyperlinks:
- {link: /vobs/porta <- /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/dev_brno_porta/5,
  nr: '1149', type: Merge}
predecessor: {branch: /main, nr: '3'}
protection:
  group: {name: PL_WRO_CC_USR, rights: r--}
  other: {name: '', rights: r--}
  user: {name: wrocc_adm, rights: r--}
type: file
version: {branch: /main, name: Makefile, nr: '4', path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html}



['2006-08-01T13:46:01+02:00', Jiri Tesar (tesarj.gs_herkules@dingo), /home/langiewi_m/p2_latest/develop/source/siemens/applications/html,
  Makefile, /main, '3']


comment: ''
creator: Jiri Tesar (tesarj.gs_herkules@dingo)
datetime: '2006-08-01T13:46:01+02:00'
elementtype: text_file
hyperlinks:
- {link: /vobs/porta <- /view/LANGIEWI_M_PORTA_BAS_052_MAINT_DEV/vobs/porta/sw/develop/source/siemens/applications/html/Makefile@@/main/dev_brno_porta/2,
  nr: '1132', type: Merge}
labels: [PORTA_TIH_BAS_020, PORTA_TIH_BAS_020_T, PORTA_BAS_020_1]
predecessor: {branch: /main, nr: '2'}
protection:
  group: {name: PL_WRO_CC_USR, rights: r--}
  other: {name: '', rights: r--}
  user: {name: wrocc_adm, rights: r--}
type: file
version: {branch: /main, name: Makefile, nr: '3', path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html}



['2006-07-12T17:58:49+02:00', ClearCase Administrator (ccadmin.ccusers@bchk081x),
  /home/langiewi_m/p2_latest/develop/source/siemens/applications/html, Makefile, /main,
  '2']


comment: '"Imported from porta_leo@@/main/PORTA_LEO_MAIN_BAS_019"'
creator: ClearCase Administrator (ccadmin.ccusers@bchk081x)
datetime: '2006-07-12T17:58:49+02:00'
elementtype: text_file
labels: [PORTA_V2_PRE_BAS_020, PORTA_BAS_020, PORTA_V1_KPN_BAS_019, PORTA_V2_PRE_BAS_019,
  PORTA_BAS_019]
predecessor: {branch: /main, nr: '1'}
protection:
  group: {name: PL_WRO_CC_USR, rights: r--}
  other: {name: '', rights: r--}
  user: {name: wrocc_adm, rights: r--}
type: file
version: {branch: /main, name: Makefile, nr: '2', path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html}



['2006-06-09T10:06:56+02:00', ClearCase Administrator (ccadmin.ccusers@bchk54zc),
  /home/langiewi_m/p2_latest/develop/source/siemens/applications/html, Makefile, /main,
  '1']


comment: '"Import from PORTA_LEO_MAIN_BAS_018"'
creator: ClearCase Administrator (ccadmin.ccusers@bchk54zc)
datetime: '2006-06-09T10:06:56+02:00'
elementtype: text_file
labels: [PORTA_BAS_018]
predecessor: {branch: /main, nr: '0'}
protection:
  group: {name: PL_WRO_CC_USR, rights: r--}
  other: {name: '', rights: r--}
  user: {name: wrocc_adm, rights: r--}
type: file
version: {branch: /main, name: Makefile, nr: '1', path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html}



['2006-06-09T10:06:56+02:00', ClearCase Administrator (ccadmin.ccusers@bchk54zc),
  /home/langiewi_m/p2_latest/develop/source/siemens/applications/html, Makefile, /main,
  '0']


comment: ''
creator: ClearCase Administrator (ccadmin.ccusers@bchk54zc)
datetime: '2006-06-09T10:06:56+02:00'
elementtype: text_file
protection:
  group: {name: PL_WRO_CC_USR, rights: r--}
  other: {name: '', rights: r--}
  user: {name: wrocc_adm, rights: r--}
type: file
version: {branch: /main, name: Makefile, nr: '0', path: /home/langiewi_m/p2_latest/develop/source/siemens/applications/html}
